name: Docker image build

on:
  push:
    tags:
      - '**'
  workflow_dispatch: ~

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v7

    - uses: docker/setup-buildx-action@v4
      name: Set up Docker Buildx
      id: buildx

    - uses: docker/build-push-action@v7
      name: Build image
      with:
        context: .
        outputs: type=docker,dest=${{ runner.temp }}/llvm-mesa-egl-image-${{ matrix.arch }}.tar
        tags: llvm-mesa-egl-image:latest-${{ matrix.arch }}

    - name: Copy Mesa EGL bundle out of Docker image
      run: |
        docker load --input ${{ runner.temp }}/llvm-mesa-egl-image-${{ matrix.arch }}.tar
        docker create --name temp-container llvm-mesa-egl-image:latest-${{ matrix.arch }}
        docker cp temp-container:/opt/mesa-egl mesa-egl
        docker rm temp-container

    - name: Set package name
      id: name
      env:
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tarname=mesa-egl-$TAG-${{ matrix.arch }}.tar.gz" >> $GITHUB_OUTPUT
        else
          echo "tarname=mesa-egl-${{ matrix.arch }}.tar.gz" >> $GITHUB_OUTPUT
        fi

    - name: Create Mesa EGL tarball
      run: |
        tar -czf ${{ steps.name.outputs.tarname }} mesa-egl

    - name: Upload Mesa EGL tarball as artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.name.outputs.tarname }}
        path: ${{ steps.name.outputs.tarname }}
        retention-days: 14

    - name: Create and upload release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v3
      with:
        fail_on_unmatched_files: true
        files: |
          ${{ steps.name.outputs.tarname }}
