name: Docker image build

on:
  push:
    tags:
      - '**'
  workflow_dispatch: ~

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v5

    - uses: docker/setup-buildx-action@v3
      name: Set up Docker Buildx
      id: buildx

    - uses: docker/build-push-action@v6
      name: Build image
      with:
        context: .
        outputs: type=docker,dest=${{ runner.temp }}/llvm-osmesa-image-${{ matrix.arch }}.tar
        tags: llvm-osmesa-image:latest-${{ matrix.arch }}

    - name: Copy OSMesa out of Docker image
      run: |
        mkdir libOSMesa
        cd libOSMesa
        docker load --input ${{ runner.temp }}/llvm-osmesa-image-${{ matrix.arch }}.tar
        docker images
        docker create --name temp-container llvm-osmesa-image:latest-${{ matrix.arch }}
        docker cp temp-container:/usr/local/lib64/libOSMesa.so.8.0.0 .
        docker cp temp-container:/usr/local/lib64/libOSMesa.so.8 .
        docker cp temp-container:/usr/local/lib64/libOSMesa.so .
        docker rm temp-container

    - name: Set package name
      id: name
      env:
        GITHUB_REF_TYPE: ${{ github.ref_type }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tarname=libOSMesa-$TAG-${{ matrix.arch }}.tar.gz" >> $GITHUB_OUTPUT
        else
          echo "tarname=libOSMesa-${{ matrix.arch }}.tar.gz" >> $GITHUB_OUTPUT
        fi

    - name: Create OSMesa tarball
      run: |
        tar -czf ${{ steps.name.outputs.tarname }} libOSMesa

    - name: Upload OSMesa tarball as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.name.outputs.tarname }}
        path: ${{ steps.name.outputs.tarname }}
        retention-days: 14

    - name: Create and upload release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        files: |
          ${{ steps.name.outputs.tarname }}
